export enum CATEGORIES  {
    ALL = "all",
    BEAUTY = "beauty",
    Fragrances = "fragrances",
    Furniture = "furniture",
    Groceries = "groceries",
    HOME_DECORATION = "home-decoration",
    KITCHES_ACCESSORIES = "kitchen-accessories",
    LAPTOP = "laptops",
    MENS_SHIRTS = "mens-shirts",
    MENS_SHOES = "mens-shoes",
    MENS_WATCHES = "mens-watches",
    MOBILE_ACCESSORIES = "mobile-accessories",
    MOTORCYCLE = "motorcycle",
    SKIN_CARE  ="skin-care",
    SMARTPHONES = "smartphones",
    SPORTS_ACCESSORIES = "sports-accessories",
    SUNGLASSES = "sunglasses",
    TABLES = "tablets",
    TOPS = "tops",
    VEHICLE = "vehicle",
    WOMENS_BAGS = "womens-bags",
    WOMENS_DRESSES = "womens-dresses",
    WOMENS_JEWELLERY = "womens-jewellery",
    WOMENS_SHOES =  "womens-shoes",
    WOMENS_WATCHES = "womens-watches"
}