enum CATEGORIES  {
    ALL = 'all',
    BEAUTY = "beauty",
    FRAGRANCES = "fragrances",
    FURNITURE = "furniture",
    GROCERIES = "groceries",
    HOMEDECORATION = "home-decoration",
    KITCHESACCESSORIES = "kitchen-accessories",
    LAPTOP = "laptops",
    MENSSHIRTS = "mens-shirts",
    MENSSHOES = "mens-shoes",
    MENSWATCHES = "mens-watches",
    MOBILEACCESSORIES = "mobile-accessories",
    MOTORCYCLE = "motorcycle",
    SKINCARE  ="skin-care",
    SMARTPHONES = "smartphones",
    SPORTSACCESSORIES = "sports-accessories",
    SUNGLASSES = "sunglasses",
    TABLES = "tablets",
    TOPS = "tops",
    VEHICLE = "vehicle",
    WOMENSBAGS = "womens-bags",
    WOMENSDRESSES = "womens-dresses",
    WOMENSJEWELLERY = "womens-jewellery",
    WOMENSSHOES =  "womens-shoes",
    WOMENSWATCHES = "womens-watches"
}
export CATEGORIES;